-- Inserir dados de exemplo usando o usuário admin existente
INSERT INTO student_registrations (
    user_id,
    full_name,
    email,
    phone,
    whatsapp,
    birth_date,
    institution_name,
    school_year,
    course_name,
    city,
    state,
    motivation
) VALUES 
(
    (SELECT id FROM profiles WHERE email = 'lailson@oxentecode.com.br' LIMIT 1),
    'Ana Silva',
    'ana.silva@exemplo.com',
    '(11) 98765-4321',
    '(11) 98765-4321',
    '2005-03-15',
    'ETEC Central',
    '3º Ano Ensino Médio',
    'Técnico em Meio Ambiente',
    'São Paulo',
    'SP',
    'Quero trabalhar com sustentabilidade'
),
(
    (SELECT id FROM profiles WHERE email = 'lailson@oxentecode.com.br' LIMIT 1),
    'Carlos Santos',
    'carlos.santos@exemplo.com',
    '(21) 99888-7777',
    '(21) 99888-7777',
    '2004-07-22',
    'IF Rio de Janeiro',
    '2º Ano Ensino Médio',
    'Técnico em Informática',
    'Rio de Janeiro',
    'RJ',
    'Interesse em tecnologia verde'
),
(
    (SELECT id FROM profiles WHERE email = 'lailson@oxentecode.com.br' LIMIT 1),
    'Maria Oliveira',
    'maria.oliveira@exemplo.com',
    '(31) 97777-6666',
    '(31) 97777-6666',
    '2006-01-10',
    'CEFET Minas Gerais',
    '1º Ano Ensino Médio',
    'Técnico em Energia Renovável',
    'Belo Horizonte',
    'MG',
    'Paixão por energia eólica'
),
(
    (SELECT id FROM profiles WHERE email = 'lailson@oxentecode.com.br' LIMIT 1),
    'João Costa',
    'joao.costa@exemplo.com',
    '(85) 96666-5555',
    '(85) 96666-5555',
    '2005-11-03',
    'IFCE Fortaleza',
    '3º Ano Ensino Médio',
    'Técnico em Eletrônica',
    'Fortaleza',
    'CE',
    'Quero desenvolver projetos sustentáveis'
),
(
    (SELECT id FROM profiles WHERE email = 'lailson@oxentecode.com.br' LIMIT 1),
    'Beatriz Lima',
    'beatriz.lima@exemplo.com',
    '(71) 95555-4444',
    '(71) 95555-4444',
    '2004-09-18',
    'IFBA Salvador',
    '2º Ano Ensino Médio',
    'Técnico em Automação',
    'Salvador',
    'BA',
    'Interesse em automação industrial verde'
);